### ISSUE TITLE
Сделайте поддержку PHP7

### ISSUE THREAD

**Issue by ptrofimov** [yandex-php/translate-api#12]
2017 год уже)))

К тому же, скорее всего, достаточно поменять версию в composer.json.

**Comment by nkt** [comment]
Отправьте PR :wink:

**Comment by ptrofimov** [comment]
Я то отправлю, но у вас тестов нет. Как узнать, что все хорошо?

**Comment by nkt** [comment]
Написать тесты

**Comment by ptrofimov** [comment]
а, я думал, судя по названию, это официально поддерживаемое api. сейчас вижу, что нет. мне то проще вообще через curl сделать. э - эффективность)))
